### ISSUE TITLE
Feature Request: Editable intake amounts/types

### ISSUE THREAD

**Issue by kennioje** [z3r0c00l-2k/AquaDroid#16]
The preset liquid intake amounts do not match my glass / mug sizes.
It would make the app much more useable if the user could customise the buttons to their environment. For example I often have a pint (uk) glass of water.

**Comment by pieqq** [comment]
The easiest way of doing this would be to add, above or below the current buttons (`200 ml aqua`, ...) an `EditText` field where user could input his desired value (in ml) with a button to add it to the amount already drunk today. If possible, this value would be kept, so that if the user always uses the same glass for instance, he doesn't have to re-type the glass amount everytime.

A more complex solution would be, as described by @kennioje, to be able to create customized buttons. That would require a separate setup screen.

**Comment by paulle** [comment]
Maybe the simplest solution is to have only 2 editable bottoms. Volume (in ml) and the type of liquid (water, coffee, juice etc.).

**Comment by pieqq** [comment]
Does the type of liquid have any influence at all or is it purely cosmetic? If it's the latter, only one text field would be enough.

**Comment by paulle** [comment]
At first it's important to drink a certain volume of liquid and for your health it will make a difference drinking water or softdrinks.

**Comment by SecT0uch** [comment]
@z3r0c00l-2k Is there any reason why did you close this issue? This function would totally makes sense.

**Comment by z3r0c00l-2k** [comment]
I am working on it... this feature will be there in near future...✌️✌️✌️

**Comment by paulle** [comment]
Can't wait to see it. Thank you very much.

Am 3. Januar 2020 02:08:31 MEZ schrieb Jabir Mohammad ACK <notifications@github.com>:
>I am working on it... this feature will be there in near
>future...✌️✌️✌️>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/z3r0c00l-2k/AquaDroid/issues/16#issuecomment-570424532

-- 
K-9 Mail
